CREATE TABLE IF NOT EXISTS `SONGS` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `label` VARCHAR(60) NOT NULL,
    `title` VARCHAR(40) NOT NULL,
    `artist` VARCHAR(40) NOT NULL,
    `image` VARCHAR(120) NOT NULL,
    `lyrics` VARCHAR(10000) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`label`)
)